[project]
name = "roboeyes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xe111", email = "2073661764@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
